### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by jantari** [gamethis/ansible_role_wsus_server#3]
Hello @gamethis 

I opened #2 a month ago and so far no response. I was forced to fork this role into a private repository and I made many many fixes and improvements to my fork that I would like to contribute back upstream here so that everyone can benefit from them - but I was wondering whether you are still maintaining this role, if not I would ask you to please archive the repository so that new people who find this role and may want to use it are aware of its abandoned state.

If you are back and interested in PRs I can make many separate ones for every fix and improvement I made.

**Comment by gamethis** [comment]
Hi @jantari yes I am interested in any fixes you may have for this.
please open separate prs for each one.

**Comment by gamethis** [comment]
this repo still maintained...

Updated settings to make sure I see issues and prs.
